apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-web
  name: events-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events-web
  strategy: {}
  template:
    metadata:
      labels:
        app: events-web
    spec:
      containers:
      - image: lmurp14/capstone-frontend:v1.0
        name: events-web
        imagePullPolicy: "Always"
        env:
        - name: SERVER
          value: "http://events-api:8082"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}